version: "3"
services:
  backend:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    command: npm start
    depends_on:
      - mongodb

  frontend:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    command: npm start

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
